{{- if .Values.topology.otel.enabled }}
{{- $otelName := include "nemo-retriever.otel.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $otelName }}-config
  labels:
    {{- include "nemo-retriever.role.labels" (dict "context" $ "role" "otel") | nindent 4 }}
data:
  config.yaml: |
    {{- include "nemo-retriever.otel.config" . | nindent 4 }}
{{- end }}
