# SPDX-FileCopyrightText: Copyright (c) 2024-26, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from nemo_retriever.adapters.cli.ingest import options as opts
from nemo_retriever.adapters.cli.ingest.shared import run_cli_workflow
from nemo_retriever.adapters.cli.ingest_workflow import run_ingest_workflow
from nemo_retriever.ingest.plan import (
    AudioSplitTypeValue,
    IngestCaptionOptions,
    IngestChunkOptions,
    IngestDedupOptions,
    IngestEmbedBatchOptions,
    IngestEmbedOptions,
    IngestExtractBatchOptions,
    IngestExtractOptions,
    IngestImageStoreOptions,
    IngestMediaOptions,
    IngestPlanRequest,
    IngestRuntimeOptions,
    IngestSourceOptions,
    IngestStorageOptions,
    LocalIngestEmbedBackendValue,
    OcrLangValue,
    OcrVersionValue,
    TableOutputFormatValue,
    resolve_ingest_plan,
)


def _run_graph_ingest_request(request: IngestPlanRequest, *, dry_run: bool, quiet: bool) -> None:
    run_cli_workflow(
        lambda: run_ingest_workflow(resolve_ingest_plan(request), dry_run=dry_run),
        quiet=quiet,
    )


def _extract_options(
    *,
    method: str | None,
    dpi: int | None,
    extract_text: bool | None,
    extract_images: bool | None,
    extract_tables: bool | None,
    extract_charts: bool | None,
    extract_infographics: bool | None,
    extract_page_as_image: bool | None,
    use_page_elements: bool | None,
    use_graphic_elements: bool | None,
    use_table_structure: bool | None,
    page_elements_invoke_url: str | None,
    ocr_invoke_url: str | None,
    ocr_version: OcrVersionValue | None,
    ocr_lang: OcrLangValue | None,
    graphic_elements_invoke_url: str | None,
    table_structure_invoke_url: str | None,
    table_output_format: TableOutputFormatValue | None,
    api_key: str | None,
    batch: IngestExtractBatchOptions | None = None,
) -> IngestExtractOptions:
    return IngestExtractOptions(
        method=method,
        dpi=dpi,
        extract_text=extract_text,
        extract_images=extract_images,
        extract_tables=extract_tables,
        extract_charts=extract_charts,
        extract_infographics=extract_infographics,
        extract_page_as_image=extract_page_as_image,
        use_page_elements=use_page_elements,
        use_graphic_elements=use_graphic_elements,
        use_table_structure=use_table_structure,
        page_elements_invoke_url=page_elements_invoke_url,
        ocr_invoke_url=ocr_invoke_url,
        ocr_version=ocr_version,
        ocr_lang=ocr_lang,
        graphic_elements_invoke_url=graphic_elements_invoke_url,
        table_structure_invoke_url=table_structure_invoke_url,
        table_output_format=table_output_format,
        extract_api_key=api_key,
        batch=batch or IngestExtractBatchOptions(),
    )


def _media_options(
    *,
    segment_audio: bool | None,
    audio_split_type: AudioSplitTypeValue,
    audio_split_interval: int | None,
    video_extract_audio: bool | None,
    video_extract_frames: bool | None,
    video_frame_fps: float | None,
    video_frame_dedup: bool | None,
    video_frame_text_dedup: bool | None,
    video_frame_text_dedup_max_dropped_frames: int | None,
    video_av_fuse: bool | None,
) -> IngestMediaOptions:
    return IngestMediaOptions(
        segment_audio=segment_audio,
        audio_split_type=audio_split_type,
        audio_split_interval=audio_split_interval,
        video_extract_audio=video_extract_audio,
        video_extract_frames=video_extract_frames,
        video_frame_fps=video_frame_fps,
        video_frame_dedup=video_frame_dedup,
        video_frame_text_dedup=video_frame_text_dedup,
        video_frame_text_dedup_max_dropped_frames=video_frame_text_dedup_max_dropped_frames,
        video_av_fuse=video_av_fuse,
    )


def _caption_options(
    *,
    caption: bool,
    api_key: str | None,
    caption_invoke_url: str | None,
    caption_model_name: str | None,
    caption_context_text_max_chars: int | None,
    caption_infographics: bool | None,
) -> IngestCaptionOptions:
    return IngestCaptionOptions(
        enabled=caption,
        caption_invoke_url=caption_invoke_url,
        caption_api_key=api_key,
        caption_model_name=caption_model_name,
        caption_context_text_max_chars=caption_context_text_max_chars,
        caption_infographics=caption_infographics,
    )


def _embed_options(
    *,
    embed_invoke_url: str | None,
    embed_model_name: str | None,
    local_ingest_embed_backend: LocalIngestEmbedBackendValue | None,
    api_key: str | None,
    embed_modality: str | None,
    embed_granularity: str | None,
    text_elements_modality: str | None,
    structured_elements_modality: str | None,
    batch: IngestEmbedBatchOptions | None = None,
) -> IngestEmbedOptions:
    return IngestEmbedOptions(
        embed_invoke_url=embed_invoke_url,
        embed_model_name=embed_model_name,
        local_ingest_embed_backend=local_ingest_embed_backend,
        embed_api_key=api_key,
        embed_modality=embed_modality,
        embed_granularity=embed_granularity,
        text_elements_modality=text_elements_modality,
        structured_elements_modality=structured_elements_modality,
        batch=batch or IngestEmbedBatchOptions(),
    )


def local_command(
    documents: opts.DocumentsArgument,
    profile: opts.ProfileOption = "auto",
    lancedb_uri: opts.LanceDbUriOption = "lancedb",
    table_name: opts.TableNameOption = "nemo-retriever",
    dry_run: opts.DryRunOption = False,
    method: opts.MethodOption = None,
    dpi: opts.DpiOption = None,
    extract_text: opts.ExtractTextOption = None,
    extract_images: opts.ExtractImagesOption = None,
    extract_tables: opts.ExtractTablesOption = None,
    extract_charts: opts.ExtractChartsOption = None,
    extract_infographics: opts.ExtractInfographicsOption = None,
    extract_page_as_image: opts.ExtractPageAsImageOption = None,
    use_page_elements: opts.UsePageElementsOption = None,
    use_graphic_elements: opts.UseGraphicElementsOption = None,
    use_table_structure: opts.UseTableStructureOption = None,
    segment_audio: opts.SegmentAudioOption = None,
    audio_split_type: opts.AudioSplitTypeOption = "size",
    audio_split_interval: opts.AudioSplitIntervalOption = None,
    video_extract_audio: opts.VideoExtractAudioOption = None,
    video_extract_frames: opts.VideoExtractFramesOption = None,
    video_frame_fps: opts.VideoFrameFpsOption = None,
    video_frame_dedup: opts.VideoFrameDedupOption = None,
    video_frame_text_dedup: opts.VideoFrameTextDedupOption = None,
    video_frame_text_dedup_max_dropped_frames: opts.VideoFrameTextDedupMaxDroppedFramesOption = None,
    video_av_fuse: opts.VideoAvFuseOption = None,
    caption: opts.CaptionOption = False,
    caption_invoke_url: opts.CaptionInvokeUrlOption = None,
    api_key: opts.ApiKeyOption = None,
    caption_model_name: opts.CaptionModelNameOption = None,
    caption_context_text_max_chars: opts.CaptionContextTextMaxCharsOption = None,
    caption_infographics: opts.CaptionInfographicsOption = None,
    dedup: opts.DedupOption = False,
    dedup_iou_threshold: opts.DedupIouThresholdOption = None,
    store_images_uri: opts.StoreImagesUriOption = None,
    overwrite: opts.OverwriteOption = True,
    page_elements_invoke_url: opts.PageElementsInvokeUrlOption = None,
    ocr_invoke_url: opts.OcrInvokeUrlOption = None,
    ocr_version: opts.OcrVersionOption = None,
    ocr_lang: opts.OcrLangOption = None,
    graphic_elements_invoke_url: opts.GraphicElementsInvokeUrlOption = None,
    table_structure_invoke_url: opts.TableStructureInvokeUrlOption = None,
    table_output_format: opts.TableOutputFormatOption = None,
    embed_invoke_url: opts.EmbedInvokeUrlOption = None,
    embed_model_name: opts.EmbedModelNameOption = None,
    local_ingest_embed_backend: opts.LocalIngestEmbedBackendOption = None,
    embed_modality: opts.EmbedModalityOption = None,
    embed_granularity: opts.EmbedGranularityOption = None,
    text_elements_modality: opts.TextElementsModalityOption = None,
    structured_elements_modality: opts.StructuredElementsModalityOption = None,
    text_chunk: opts.TextChunkOption = False,
    text_chunk_max_tokens: opts.TextChunkMaxTokensOption = None,
    text_chunk_overlap_tokens: opts.TextChunkOverlapTokensOption = None,
    quiet: opts.QuietOption = True,
) -> None:
    request = IngestPlanRequest(
        source=IngestSourceOptions(documents=documents, profile=profile),
        runtime=IngestRuntimeOptions(run_mode="inprocess"),
        extract=_extract_options(
            method=method,
            dpi=dpi,
            extract_text=extract_text,
            extract_images=extract_images,
            extract_tables=extract_tables,
            extract_charts=extract_charts,
            extract_infographics=extract_infographics,
            extract_page_as_image=extract_page_as_image,
            use_page_elements=use_page_elements,
            use_graphic_elements=use_graphic_elements,
            use_table_structure=use_table_structure,
            page_elements_invoke_url=page_elements_invoke_url,
            ocr_invoke_url=ocr_invoke_url,
            ocr_version=ocr_version,
            ocr_lang=ocr_lang,
            graphic_elements_invoke_url=graphic_elements_invoke_url,
            table_structure_invoke_url=table_structure_invoke_url,
            table_output_format=table_output_format,
            api_key=api_key,
        ),
        media=_media_options(
            segment_audio=segment_audio,
            audio_split_type=audio_split_type,
            audio_split_interval=audio_split_interval,
            video_extract_audio=video_extract_audio,
            video_extract_frames=video_extract_frames,
            video_frame_fps=video_frame_fps,
            video_frame_dedup=video_frame_dedup,
            video_frame_text_dedup=video_frame_text_dedup,
            video_frame_text_dedup_max_dropped_frames=video_frame_text_dedup_max_dropped_frames,
            video_av_fuse=video_av_fuse,
        ),
        caption=_caption_options(
            caption=caption,
            api_key=api_key,
            caption_invoke_url=caption_invoke_url,
            caption_model_name=caption_model_name,
            caption_context_text_max_chars=caption_context_text_max_chars,
            caption_infographics=caption_infographics,
        ),
        dedup=IngestDedupOptions(enabled=dedup, iou_threshold=dedup_iou_threshold),
        chunk=IngestChunkOptions(
            enabled=text_chunk,
            text_chunk_max_tokens=text_chunk_max_tokens,
            text_chunk_overlap_tokens=text_chunk_overlap_tokens,
        ),
        embed=_embed_options(
            embed_invoke_url=embed_invoke_url,
            embed_model_name=embed_model_name,
            local_ingest_embed_backend=local_ingest_embed_backend,
            api_key=api_key,
            embed_modality=embed_modality,
            embed_granularity=embed_granularity,
            text_elements_modality=text_elements_modality,
            structured_elements_modality=structured_elements_modality,
        ),
        image_store=IngestImageStoreOptions(images_uri=store_images_uri),
        storage=IngestStorageOptions(lancedb_uri=lancedb_uri, table_name=table_name, overwrite=overwrite),
    )
    _run_graph_ingest_request(request, dry_run=dry_run, quiet=quiet)


def batch_command(
    documents: opts.DocumentsArgument,
    profile: opts.ProfileOption = "auto",
    lancedb_uri: opts.LanceDbUriOption = "lancedb",
    table_name: opts.TableNameOption = "nemo-retriever",
    dry_run: opts.DryRunOption = False,
    method: opts.MethodOption = None,
    dpi: opts.DpiOption = None,
    extract_text: opts.ExtractTextOption = None,
    extract_images: opts.ExtractImagesOption = None,
    extract_tables: opts.ExtractTablesOption = None,
    extract_charts: opts.ExtractChartsOption = None,
    extract_infographics: opts.ExtractInfographicsOption = None,
    extract_page_as_image: opts.ExtractPageAsImageOption = None,
    use_page_elements: opts.UsePageElementsOption = None,
    use_graphic_elements: opts.UseGraphicElementsOption = None,
    use_table_structure: opts.UseTableStructureOption = None,
    segment_audio: opts.SegmentAudioOption = None,
    audio_split_type: opts.AudioSplitTypeOption = "size",
    audio_split_interval: opts.AudioSplitIntervalOption = None,
    video_extract_audio: opts.VideoExtractAudioOption = None,
    video_extract_frames: opts.VideoExtractFramesOption = None,
    video_frame_fps: opts.VideoFrameFpsOption = None,
    video_frame_dedup: opts.VideoFrameDedupOption = None,
    video_frame_text_dedup: opts.VideoFrameTextDedupOption = None,
    video_frame_text_dedup_max_dropped_frames: opts.VideoFrameTextDedupMaxDroppedFramesOption = None,
    video_av_fuse: opts.VideoAvFuseOption = None,
    caption: opts.CaptionOption = False,
    caption_invoke_url: opts.CaptionInvokeUrlOption = None,
    api_key: opts.ApiKeyOption = None,
    caption_model_name: opts.CaptionModelNameOption = None,
    caption_context_text_max_chars: opts.CaptionContextTextMaxCharsOption = None,
    caption_infographics: opts.CaptionInfographicsOption = None,
    dedup: opts.DedupOption = False,
    dedup_iou_threshold: opts.DedupIouThresholdOption = None,
    store_images_uri: opts.StoreImagesUriOption = None,
    overwrite: opts.OverwriteOption = True,
    ray_address: opts.RayAddressOption = None,
    ray_log_to_driver: opts.RayLogToDriverOption = None,
    page_elements_invoke_url: opts.PageElementsInvokeUrlOption = None,
    ocr_invoke_url: opts.OcrInvokeUrlOption = None,
    ocr_version: opts.OcrVersionOption = None,
    ocr_lang: opts.OcrLangOption = None,
    graphic_elements_invoke_url: opts.GraphicElementsInvokeUrlOption = None,
    table_structure_invoke_url: opts.TableStructureInvokeUrlOption = None,
    table_output_format: opts.TableOutputFormatOption = None,
    embed_invoke_url: opts.EmbedInvokeUrlOption = None,
    embed_model_name: opts.EmbedModelNameOption = None,
    local_ingest_embed_backend: opts.LocalIngestEmbedBackendOption = None,
    embed_modality: opts.EmbedModalityOption = None,
    embed_granularity: opts.EmbedGranularityOption = None,
    text_elements_modality: opts.TextElementsModalityOption = None,
    structured_elements_modality: opts.StructuredElementsModalityOption = None,
    text_chunk: opts.TextChunkOption = False,
    text_chunk_max_tokens: opts.TextChunkMaxTokensOption = None,
    text_chunk_overlap_tokens: opts.TextChunkOverlapTokensOption = None,
    pdf_split_batch_size: opts.PdfSplitBatchSizeOption = None,
    pdf_extract_workers: opts.PdfExtractWorkersOption = None,
    pdf_extract_batch_size: opts.PdfExtractBatchSizeOption = None,
    pdf_extract_cpus_per_task: opts.PdfExtractCpusPerTaskOption = None,
    page_elements_workers: opts.PageElementsWorkersOption = None,
    page_elements_batch_size: opts.PageElementsBatchSizeOption = None,
    page_elements_cpus_per_actor: opts.PageElementsCpusPerActorOption = None,
    page_elements_gpus_per_actor: opts.PageElementsGpusPerActorOption = None,
    ocr_workers: opts.OcrWorkersOption = None,
    ocr_batch_size: opts.OcrBatchSizeOption = None,
    ocr_cpus_per_actor: opts.OcrCpusPerActorOption = None,
    ocr_gpus_per_actor: opts.OcrGpusPerActorOption = None,
    table_structure_workers: opts.TableStructureWorkersOption = None,
    table_structure_batch_size: opts.TableStructureBatchSizeOption = None,
    table_structure_cpus_per_actor: opts.TableStructureCpusPerActorOption = None,
    table_structure_gpus_per_actor: opts.TableStructureGpusPerActorOption = None,
    nemotron_parse_workers: opts.NemotronParseWorkersOption = None,
    nemotron_parse_batch_size: opts.NemotronParseBatchSizeOption = None,
    nemotron_parse_gpus_per_actor: opts.NemotronParseGpusPerActorOption = None,
    embed_workers: opts.EmbedWorkersOption = None,
    embed_batch_size: opts.EmbedBatchSizeOption = None,
    embed_cpus_per_actor: opts.EmbedCpusPerActorOption = None,
    embed_gpus_per_actor: opts.EmbedGpusPerActorOption = None,
    quiet: opts.QuietOption = True,
) -> None:
    extract_batch = IngestExtractBatchOptions(
        pdf_split_batch_size=pdf_split_batch_size,
        pdf_extract_workers=pdf_extract_workers,
        pdf_extract_batch_size=pdf_extract_batch_size,
        pdf_extract_cpus_per_task=pdf_extract_cpus_per_task,
        page_elements_workers=page_elements_workers,
        page_elements_batch_size=page_elements_batch_size,
        page_elements_cpus_per_actor=page_elements_cpus_per_actor,
        page_elements_gpus_per_actor=page_elements_gpus_per_actor,
        ocr_workers=ocr_workers,
        ocr_batch_size=ocr_batch_size,
        ocr_cpus_per_actor=ocr_cpus_per_actor,
        ocr_gpus_per_actor=ocr_gpus_per_actor,
        table_structure_workers=table_structure_workers,
        table_structure_batch_size=table_structure_batch_size,
        table_structure_cpus_per_actor=table_structure_cpus_per_actor,
        table_structure_gpus_per_actor=table_structure_gpus_per_actor,
        nemotron_parse_workers=nemotron_parse_workers,
        nemotron_parse_batch_size=nemotron_parse_batch_size,
        nemotron_parse_gpus_per_actor=nemotron_parse_gpus_per_actor,
    )
    embed_batch = IngestEmbedBatchOptions(
        embed_workers=embed_workers,
        embed_batch_size=embed_batch_size,
        embed_cpus_per_actor=embed_cpus_per_actor,
        embed_gpus_per_actor=embed_gpus_per_actor,
    )
    request = IngestPlanRequest(
        source=IngestSourceOptions(documents=documents, profile=profile),
        runtime=IngestRuntimeOptions(
            run_mode="batch",
            ray_address=ray_address,
            ray_log_to_driver=ray_log_to_driver,
        ),
        extract=_extract_options(
            method=method,
            dpi=dpi,
            extract_text=extract_text,
            extract_images=extract_images,
            extract_tables=extract_tables,
            extract_charts=extract_charts,
            extract_infographics=extract_infographics,
            extract_page_as_image=extract_page_as_image,
            use_page_elements=use_page_elements,
            use_graphic_elements=use_graphic_elements,
            use_table_structure=use_table_structure,
            page_elements_invoke_url=page_elements_invoke_url,
            ocr_invoke_url=ocr_invoke_url,
            ocr_version=ocr_version,
            ocr_lang=ocr_lang,
            graphic_elements_invoke_url=graphic_elements_invoke_url,
            table_structure_invoke_url=table_structure_invoke_url,
            table_output_format=table_output_format,
            api_key=api_key,
            batch=extract_batch,
        ),
        media=_media_options(
            segment_audio=segment_audio,
            audio_split_type=audio_split_type,
            audio_split_interval=audio_split_interval,
            video_extract_audio=video_extract_audio,
            video_extract_frames=video_extract_frames,
            video_frame_fps=video_frame_fps,
            video_frame_dedup=video_frame_dedup,
            video_frame_text_dedup=video_frame_text_dedup,
            video_frame_text_dedup_max_dropped_frames=video_frame_text_dedup_max_dropped_frames,
            video_av_fuse=video_av_fuse,
        ),
        caption=_caption_options(
            caption=caption,
            api_key=api_key,
            caption_invoke_url=caption_invoke_url,
            caption_model_name=caption_model_name,
            caption_context_text_max_chars=caption_context_text_max_chars,
            caption_infographics=caption_infographics,
        ),
        dedup=IngestDedupOptions(enabled=dedup, iou_threshold=dedup_iou_threshold),
        chunk=IngestChunkOptions(
            enabled=text_chunk,
            text_chunk_max_tokens=text_chunk_max_tokens,
            text_chunk_overlap_tokens=text_chunk_overlap_tokens,
        ),
        embed=_embed_options(
            embed_invoke_url=embed_invoke_url,
            embed_model_name=embed_model_name,
            local_ingest_embed_backend=local_ingest_embed_backend,
            api_key=api_key,
            embed_modality=embed_modality,
            embed_granularity=embed_granularity,
            text_elements_modality=text_elements_modality,
            structured_elements_modality=structured_elements_modality,
            batch=embed_batch,
        ),
        image_store=IngestImageStoreOptions(images_uri=store_images_uri),
        storage=IngestStorageOptions(lancedb_uri=lancedb_uri, table_name=table_name, overwrite=overwrite),
    )
    _run_graph_ingest_request(request, dry_run=dry_run, quiet=quiet)
